# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_LMS_timesTwo', PACKAGE = 'LMS', x)
}

workerFEupdate <- function(l) {
    .Call('_LMS_workerFEupdate', PACKAGE = 'LMS', l)
}

firmFEupdate <- function(l) {
    .Call('_LMS_firmFEupdate', PACKAGE = 'LMS', l)
}

#' Computes spell length within unit
#' 
#' Within unit_id, this will create a counter that updates
#' when the variable stayer_var changes for when a time is missing
#'
#' @param unit_id An integer vector with the ID of the unit we consider
#' @param time An integer vector with the time considered
#' @param stayer_var  An integer with the variable that needs to stay constant
#' 
#' @export
computeSpellTime <- function(unit_id, time, stayer_var) {
    .Call('_LMS_computeSpellTime', PACKAGE = 'LMS', unit_id, time, stayer_var)
}

#' Computes spell ID
#' 
#' Within unit_id, this will create a counter that updates
#' when the variable stayer_var changes for when a time is missing
#'
#' @param unit_id An integer vector with the ID of the unit we consider
#' @param time An integer vector with the time considered
#' @param stayer_var  An integer with the variable that needs to stay constant
#' 
#' @export
computeSpellID <- function(unit_id, time, stayer_var) {
    .Call('_LMS_computeSpellID', PACKAGE = 'LMS', unit_id, time, stayer_var)
}

#' Computes the minimum distance to the end of a spell
#' 
#' Within unit_id, this will create a counter that updates
#' when the variable stayer_var changes for when a time is missing
#'
#' @param unit_id An integer vector with the ID of the unit we consider
#' @param time An integer vector with the time considered
#' @param stayer_var  An integer with the variable that needs to stay constant
#' @param spell_end  An integer with end of spell location
#' 
#' @export
computeDistanceToSpellEnd <- function(unit_id, time, stayer_var, spell_end) {
    .Call('_LMS_computeDistanceToSpellEnd', PACKAGE = 'LMS', unit_id, time, stayer_var, spell_end)
}

