// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _LMS_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// workerFEupdate
NumericVector workerFEupdate(List l);
RcppExport SEXP _LMS_workerFEupdate(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(workerFEupdate(l));
    return rcpp_result_gen;
END_RCPP
}
// firmFEupdate
NumericVector firmFEupdate(List l);
RcppExport SEXP _LMS_firmFEupdate(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(firmFEupdate(l));
    return rcpp_result_gen;
END_RCPP
}
// computeSpellTime
IntegerVector computeSpellTime(IntegerVector unit_id, IntegerVector time, IntegerVector stayer_var);
RcppExport SEXP _LMS_computeSpellTime(SEXP unit_idSEXP, SEXP timeSEXP, SEXP stayer_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type unit_id(unit_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stayer_var(stayer_varSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSpellTime(unit_id, time, stayer_var));
    return rcpp_result_gen;
END_RCPP
}
// computeSpellID
IntegerVector computeSpellID(IntegerVector unit_id, IntegerVector time, IntegerVector stayer_var);
RcppExport SEXP _LMS_computeSpellID(SEXP unit_idSEXP, SEXP timeSEXP, SEXP stayer_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type unit_id(unit_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stayer_var(stayer_varSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSpellID(unit_id, time, stayer_var));
    return rcpp_result_gen;
END_RCPP
}
// computeDistanceToSpellEnd
IntegerVector computeDistanceToSpellEnd(IntegerVector unit_id, IntegerVector time, IntegerVector stayer_var, IntegerVector spell_end);
RcppExport SEXP _LMS_computeDistanceToSpellEnd(SEXP unit_idSEXP, SEXP timeSEXP, SEXP stayer_varSEXP, SEXP spell_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type unit_id(unit_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stayer_var(stayer_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spell_end(spell_endSEXP);
    rcpp_result_gen = Rcpp::wrap(computeDistanceToSpellEnd(unit_id, time, stayer_var, spell_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LMS_timesTwo", (DL_FUNC) &_LMS_timesTwo, 1},
    {"_LMS_workerFEupdate", (DL_FUNC) &_LMS_workerFEupdate, 1},
    {"_LMS_firmFEupdate", (DL_FUNC) &_LMS_firmFEupdate, 1},
    {"_LMS_computeSpellTime", (DL_FUNC) &_LMS_computeSpellTime, 3},
    {"_LMS_computeSpellID", (DL_FUNC) &_LMS_computeSpellID, 3},
    {"_LMS_computeDistanceToSpellEnd", (DL_FUNC) &_LMS_computeDistanceToSpellEnd, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_LMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
